services:
  # Next.js application service
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_SERVER_HOST=chromadb
      - CHROMA_SERVER_PORT=8000
      - NODE_ENV=production
      - PORT=3000
      - API_KEY=${API_KEY}
    depends_on:
      - chromadb
    networks:
      - app-network

  # ChromaDB service
  chromadb:
    build:
      context: .
      dockerfile: Dockerfile.chromadb
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/app/chroma-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  chroma-data:
    driver: local 